### ISSUE TITLE
Uncaught TypeError: $(...).gantt is not a function

### ISSUE THREAD

**Issue by macagua** [funbaker/odoo-web_gantt#2]
I have Odoo Version 9.0c (Community Edition) downloaded from the Github repo, then I put the **"web_gantt"** module into **"addon"** directory.

This module was installed from **"Apps"** view, and later I reload my **Session Gantt view** for my **OpenAcademy** module, it's show the follow _Odoo Client Error_:

```
Odoo Client Error
Uncaught TypeError: $(...).gantt is not a function
http://127.0.0.1:8069/web_gantt/static/src/js/gantt.js:106
Traceback:
TypeError: $(...).gantt is not a function
    at Object.<anonymous> (http://127.0.0.1:8069/web_gantt/static/src/js/gantt.js:106:28)
    at fire (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.self.fireWith [as resolveWith] (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3283:104)
    at fire (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.self.fireWith [as resolveWith] (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3321:62)
    at fire (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.self.fireWith [as resolveWith] (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3283:104)
```

The same errors were captured at browsers:
- Chromium Version 47.0.2526.80 Built on 8.2, running on Debian 8.2 (64-bit)
- Mozilla Iceweasel 38.5.0, running on Debian 8.2 (64-bit)

Any idea how fix?

**Comment by macagua** [comment]
@funbaker maybe it's what happened https://github.com/taitems/jQuery.Gantt/issues/187

**Comment by funbaker** [comment]
There was some weird issue with branching going on. Absence of mind on my side. It is fixed in the master branch now.

**Comment by macagua** [comment]
@funbaker ok please, other weird issue is the view CSS check out this

![screenshot from 2016-01-28 12 27 24](https://cloud.githubusercontent.com/assets/185395/12657208/5579b9be-c5d4-11e5-8daa-2bb8774de636.png)

**Comment by funbaker** [comment]
Well i didnt have time to fix that yet, as it is kind of non-trivial.
